name: Python package

on:
  push:
    tags:
    - workflow_test

jobs:
  build:

    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - run: brew install pyenv
    - run: brew install pyenv-virtualenv
    
    - run: build/build_jaxlib_wheels_macos.sh
    
    - uses: actions/upload-artifact@master
      with:
        name: wheels
        path: build/dist/
